---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Hello
  labels:
    app: Hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Hello
  template:
    metadata:
      labels:
        app: Hello
    spec:
      containers:
        - name: Hello
          image: username/Hello:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: World
  labels:
    app: World
spec:
  replicas: 1
  selector:
    matchLabels:
      app: World
  template:
    metadata:
      labels:
        app: World
    spec:
      containers:
        - name: World
          image: username/World:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Hello
  labels:
    app: Hello
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Hello


---


apiVersion: v1
kind: Service
metadata:
  name: World
  labels:
    app: World
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: World

